# Name of the GitHub Actions workflow
name: Build and Release

# Trigger the workflow when a new tag is created
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-release:
    # Use a Windows runner for creating the Windows executable
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[build,dev]

      # --- NEW STEP: RUN TESTS ---
      # Step 4: Run tests with pytest
      # If this step fails, the workflow will stop here, and no release will be created.
      - name: Run tests
        run: pytest

      # Step 5: Build the executable using PyInstaller
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name ShiftScheduler --icon=assets/icon.ico src/shift_scheduler/main.py

      # Step 6: Get the version number from the tag
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${{ github.ref_name }}" >> $env:GITHUB_OUTPUT

      # Step 7: Create the ZIP files for the release
      - name: Package release assets
        run: |
          Compress-Archive -Path dist/ShiftScheduler.exe -DestinationPath ShiftScheduler-${{ steps.get_version.outputs.VERSION }}-windows.zip
          Compress-Archive -Path src/, docs/, assets/, pyproject.toml, README.md -DestinationPath source-code-${{ steps.get_version.outputs.VERSION }}.zip
          
      # Step 8: Create a GitHub Release and upload the ZIP files
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ShiftScheduler-${{ steps.get_version.outputs.VERSION }}-windows.zip
            source-code-${{ steps.get_version.outputs.VERSION }}.zip
          name: "Release ${{ steps.get_version.outputs.VERSION }}"
          body_path: CHANGELOG.md